fix "daemon.login" passing mandatory "client_version" parameter
t3hk0d3/deluge-api pull request #6
Opened 2022-02-21 16:25 UTC by acavalin

This patch fixes ISSUE #4 `Deluge::Rpc::Connection::RPCError (IncompatibleClient)`

Deluge version 2 now requires a client_version upon daemon.login method call.

I also added some useful external links in README.md

2022-02-22 12:19 UTC, t3hk0d3 requested changes

2022-02-22 12:19 UTC, t3hk0d3 commented on lib/deluge/rpc/connection.rb
> +        kwargs['client_version'] = Deluge::Rpc::VERSION.to_s if method == 'daemon.login'
I suggest adding it to `authenticate` method, rather than `call` method. This will keep flexibility for advanced users to send any parameters they want.

2022-02-22 16:33 UTC, merged

2022-02-22 16:33 UTC, t3hk0d3 commented
Thanks for contribution!

2023-03-05 00:09 UTC, tprepper commented
Hm, this patch doesn't seem to be in the version I got by running `gem install deluge-rpc`

2023-03-06 11:13 UTC, t3hk0d3 commented
@tprepper fixed